name: Copy README.md

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  copy-readme-file:
    name: Copy README.md to Team1.readme
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy README.md to Team1.readme
      run: cp README.md Team1.readme

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Team1.readme
        git diff --staged --quiet || git commit -m 'Update Team1.readme'
        git push
